# This is a basic workflow to help you get started with Actions
name: Format Scripts

# Controls when the action will run. 
on:
  push:
    branches:
      - "**"
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to the scripts directory'
        required: true
        default: './Assets/Scripts/'
      check_only:
        description: 'Check only without making changes'
        required: false
        default: 'false'
      diff_check:
        description: 'Whether to check only changed lines or all files'
        required: false
        default: 'false'
      check_severity:
        description: 'Severity of style checks'
        required: false
        default: 'error'
      squash_commit:
        description: 'Whether to squash commits or not'
        required: false
        default: 'false'



jobs:
  auto-formatting: # This workflow contains a single job called "auto-formatting"
    # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    runs-on: ubuntu-latest # The type of runner that the job will run on
    permissions:
      contents: write  # Allows reading and writing to the repo
      pull-requests: write  # Allows modifying PRs if necessary

    steps:
      - uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        with:
          fetch-depth: 2  # Needed if you want to amend the last commit (e.g. for squash commits)

      # Runs a single command using the runners shell
      - name: Unity Auto Format
        uses: SilvaUnCompte/CS-Unity-Actions-Autoformat@v1.1.0 # check available version before using
        with:
          path: ./Assets/Scripts/ # Path to your scripts directory
          check_only: 'false' # Set to 'true' to only verify formatting without making changes (true|false, default: 'false')
          diff_check: 'false' # Set to 'true' to check only changed files, 'false' to check all files (true|false, default: 'false')
          check_severity: 'error' # Set to 'warn' or 'error' to specify the severity of style checks (warn|error, default: 'error')
          squash_commit: 'true' # Set to 'true' to edit the previous commit instead of creating a new one (true|false, default: 'false')
