# This is a basic workflow to help you get started with Actions
name: Format Scripts

# Controls when the action will run. 
on:
  push:
    branches:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  auto-formatting: # This workflow contains a single job called "auto-formatting"
    
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Unity Auto Format
        uses: SilvaUnCompte/CS-Unity-Actions-Autoformat@v1.0.0 # check available version before using
        with:
          path: ./Assets/Scripts/ # Path to your scripts directory
          check-only: 'false' # Set to 'true' to only verify formatting without making changes (true|false, default: 'false')
          squash-commit: 'true' # Set to 'true' to edit the previous commit instead of creating a new one (true|false, default: 'false')